
stages:
    - dev
    - deploy
dev:
    stage: dev

    script:
        - echo "Building deploy package"
        - which python3
        # - npm install
        # - npm run dev
        - echo "Build successful"

# deploy_production:
#     stage: deploy

#     script:
#         - echo "Deploying to server"
#         - npm start
#         - echo "Deployed"
