stages:
  - build
  - test

job_build:
  stage: build
  script:
    - cd /home/website/kiraka
    - npm run build
    - echo "Building the project"

job_test:
  stage: test
  script:
    - echo "Running tests"
